### PR TITLE
TDL-14465: future bookmark case and start date and bookmark case

### PR DESCRIPTION
**Pull request by namrata270998**
# Description of change
As a part of this task, we have checked that all the best practices are already covered in the code. However, the two automation test cases added here were written as a part of manual test cases and we found out that they can be automated. As a result, we have tried to automate the below files with their mentioned test cases to increase the tap score.

test_quickbooks_future_date_bookmark.py 
- This file covers the future bookmark date test case which suggests that if a future bookmark date is passed, then no new bookmark should be created.

tests/test_quickbooks_bookmark_and_start_date.py
- This file covers the test case where both bookmark and start date are passed, the tap should consider the bookmark value.

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Review by kspeer825 — CHANGES_REQUESTED** [review]
I don't believe the tests here cover the work described in https://jira.talendforge.org/browse/TDL-14465. For the most up-to-date standards for writing tap-tester please see https://github.com/stitchdata/tap-tester/tree/master/reference/expectations.

**Comment by namrata270998** [comment]
> I don't believe the tests here cover the work described in https://jira.talendforge.org/browse/TDL-14465. For the most up-to-date standards for writing tap-tester please see https://github.com/stitchdata/tap-tester/tree/master/reference/expectations.

**Comment by namrata270998** [comment]
> I don't believe the tests here cover the work described in https://jira.talendforge.org/browse/TDL-14465. For the most up-to-date standards for writing tap-tester please see https://github.com/stitchdata/tap-tester/tree/master/reference/expectations.

The test cases were already covered as a part of est practices. The new files added are extra manual test cases written by our QA which we found can be automated to increase the tap score.

**Review by kspeer825 — COMMENTED** [review]
I am not sure I understand the value of this test case. The start date is persisted in our connections database. It is a required field to generate a connection. So that value will be present for every discovery and every sync regardless of state. I think this test case is implicitly covered by the existing bookmarks test.

**Comment by namrata270998** [comment]
> I am not sure I understand the value of this test case. The start date is persisted in our connections database. It is a required field to generate a connection. So that value will be present for every discovery and every sync regardless of state. I think this test case is implicitly covered by the existing bookmarks test.

Thank you for highlighting this point. I probably might have missed this case, and after looking at the existing bookmarks case, the testcase covered in the current PR would not be of any use. So we'll remove it.

**Comment by namrata270998** [comment]
Closing this pull request as the changes done are no longer required according to the pertaining discussions.

**Pull request closed without merging**
